### ISSUE TITLE
你好，为什么我在MSSA中加入LMMD效果会突然变差？

### ISSUE THREAD

**Issue by yin66-qc** [Feaxure-fresh/TL-Fault-Diagnosis-Library#13]

**Comment by Feaxure-fresh** [comment]
我们最近在[DSAN](https://github.com/Ryan906k9/DSAN)找到了LMMD的源码，之前代码中注释掉的LMMD是我们自己复现的，所以可能与实际LMMD有偏差。我们正在尝试将DSAN中的LMMD适配代码框架，并引入到MSSA中。

**Comment by Feaxure-fresh** [comment]
DSAN中的LMMD已经适配代码框架并引入到MSSA中。
