### ISSUE TITLE
你好，我没有找到Dataset-TL-FD-Library.zip在哪

### ISSUE THREAD

**Issue by Wenbo-Qin** [Feaxure-fresh/TL-Fault-Diagnosis-Library#15]
我找了文件下面的所有文件夹，都没有找到它。可以告诉我它是否在更新的时候被移动或者被删除了，我应该如何获取它呢，谢谢！

**Comment by Feaxure-fresh** [comment]
在该repository的Releases里，通常来说，您可以在GitHub页面的右侧找到它。

**Comment by Wenbo-Qin** [comment]
谢谢你的帮助，我成功找到了它。

**Comment by BayesianNetwork** [comment]
你好，这个模型训练好了，新来数据怎么测试啊？

**Comment by Feaxure-fresh** [comment]
使用# Load trained weights中介绍的方法加载模型权重进行测试，数据在运行时会根据你定义的source和target自动加载，target就是你所要测试的新数据，如果是未适配来源的数据首先要考虑是否使用# Custom Dataset Integration中的方法自定义数据加载方式。

**Comment by BayesianNetwork** [comment]
好的，谢谢啦
