### ISSUE TITLE
dataset repository is not exist

### ISSUE THREAD

**Issue by bfuyhy** [Feaxure-fresh/TL-Fault-Diagnosis-Library#17]
“Still confused about the dataset setup? Please refer to the sample datasets provided in [this repository](https://github.com/Feaxure-fresh/Dataset-TL-BFD).” However, I can't open the repository, it seems not exist.

**Comment by Feaxure-fresh** [comment]
I just wonder where you found this sentence. In the latest version of this repository, we have already changed this sentence to "Still confused about the dataset setup? Please refer to the sample datasets in the 'Releases' named Dataset-TL-FD-Library.zip".

**Comment by bfuyhy** [comment]
Thanks, I get it！
